/**
 * careerIntelligence — typed client for the new Career Intelligence endpoint.
 *
 * The PHP endpoint `/api/ai-career-intelligence` is designed to ALWAYS return
 * 200 with a rich `sections` payload — either generated by Groq AI or by a
 * deterministic fallback when Groq is unavailable / cold-start. The client
 * therefore never throws on transport errors: it converts any failure into
 * a degraded CIResponse so the page can still render with safe copy.
 *
 * Returns:
 *   - A fully typed `CIResponse` on success
 *   - A `degraded: true` `CIResponse` (with `degraded_reason` set) on any
 *     HTTP / network / parse error
 */

import { apiUrl } from '../config/api';
import { getAccessToken } from './auth';

export interface CIStrength {
  skill: string;
  score: number;
  reason: string;
}

export interface CISkillGap {
  skill: string;
  current_level: number;
  gap_level: number;
  priority: 'high' | 'medium' | 'low';
  recommendation: string;
}

export interface CICareerMatch {
  role: string;
  match_percentage: number;
  reason: string;
  missing_skills: string[];
  next_step: string;
}

export interface CIMarketReadiness {
  score: number;
  summary: string;
}

export interface CIImprovementPlan {
  days_30: string[];
  days_60: string[];
  days_90: string[];
}

export interface CISections {
  career_summary: string;
  career_level: string;
  overall_score: number;
  employability_score: number;
  hiring_readiness: number;
  top_strengths: CIStrength[];
  skill_gaps: CISkillGap[];
  career_matches: CICareerMatch[];
  market_readiness: CIMarketReadiness;
  improvement_plan: CIImprovementPlan;
  ai_summary: string;
}

export interface CIBaseline {
  employability_score: number;
  hiring_probability: number;
  career_readiness: number;
  technical_strength: number;
  soft_skill_strength: number;
  employability_label: number;
  employability_label_name: string;
  model_version: string;
  selected_regressor: string;
  selected_classifier: string;
}

export interface CIMeta {
  cache_hit: boolean;
  signature: string;
  elapsed_ms: number;
  engine: string;
  model_version: string;
  degraded_reason: string | null;
}

export interface CIResponse {
  ok: true;
  cached: boolean;
  degraded: boolean;
  profile_signature: string;
  sections: CISections;
  baseline: CIBaseline;
  meta: CIMeta;
}

async function bearer(): Promise<Record<string, string>> {
  const t = await getAccessToken();
  return t ? { Authorization: `Bearer ${t}` } : {};
}

export async function fetchCareerIntelligence(force = false): Promise<CIResponse> {
  // never throws — always returns a CIResponse with degraded fallback
  try {
    const headers = { ...(await bearer()) };
    const url = apiUrl(`/api/ai-career-intelligence${force ? '?force=true' : ''}`);
    const res = await fetch(url, { headers, method: 'GET' });
    if (!res.ok) {
      return ciEmptyResponse('http_' + res.status);
    }
    const text = await res.text();
    const data = text ? JSON.parse(text) : {};
    if (!data?.ok || !data?.sections) {
      return ciEmptyResponse('invalid_payload');
    }
    return data as CIResponse;
  } catch (e) {
    return ciEmptyResponse('network_error');
  }
}

function ciEmptyResponse(reason: string): CIResponse {
  return {
    ok: true,
    cached: false,
    degraded: true,
    profile_signature: '',
    sections: {
      career_summary:
        'No profile data yet. Add skills, take assessments, and complete your profile to unlock your Career Intelligence analysis.',
      career_level: 'Entry',
      overall_score: 0,
      employability_score: 0,
      hiring_readiness: 0,
      top_strengths: [
        {
          skill: 'Profile completeness',
          score: 0,
          reason:
            'Your profile is not yet filled in. Add skills and experience to surface real strengths.',
        },
      ],
      skill_gaps: [
        {
          skill: 'Profile data',
          current_level: 0,
          gap_level: 100,
          priority: 'high',
          recommendation: 'Complete your profile: add at least 5 skills and a short bio.',
        },
      ],
      career_matches: [
        {
          role: 'Entry-level Position',
          match_percentage: 50,
          reason: 'Default match shown while your profile loads.',
          missing_skills: ['Communication', 'Problem solving'],
          next_step: 'Add skills, experience and your job category to see real matches.',
        },
        {
          role: 'Customer Support Specialist',
          match_percentage: 40,
          reason: 'Default match shown while your profile loads.',
          missing_skills: ['English proficiency'],
          next_step: 'Take an AI interview to surface communication skills.',
        },
        {
          role: 'Administrative Assistant',
          match_percentage: 30,
          reason: 'Default match shown while your profile loads.',
          missing_skills: ['MS Office', 'Communication'],
          next_step: 'Complete your profile to see real matches.',
        },
      ],
      market_readiness: {
        score: 0,
        summary:
          'Your market readiness will appear here once your profile has real data.',
      },
      improvement_plan: {
        days_30: ['Complete your SkillProof profile', 'Add at least 5 verified skills'],
        days_60: ['Take a SkillProof assessment in your career category', 'Complete one AI interview'],
        days_90: ['Earn a Skill Passport', 'Apply to 3 jobs in your category'],
      },
      ai_summary:
        'Once your profile has real data, the AI will generate a recruiter-style summary of your readiness for the Bangladesh job market.',
    },
    baseline: {
      employability_score: 0,
      hiring_probability: 0,
      career_readiness: 0,
      technical_strength: 0,
      soft_skill_strength: 0,
      employability_label: 0,
      employability_label_name: 'Not Ready',
      model_version: 'skillproof-ml-v2',
      selected_regressor: 'weighted-feature-v2',
      selected_classifier: 'threshold-v2',
    },
    meta: {
      cache_hit: false,
      signature: '',
      elapsed_ms: 0,
      engine: 'skillproof-career-intelligence-v2',
      model_version: 'skillproof-ml-v2',
      degraded_reason: reason,
    },
  };
}