/**
 * Premium Enterprise Passport download — PDF + PNG.
 *
 * Renders the on-screen VIP passport card (with QR, verification URL,
 * seal, digital signature, passport ID) into a high-resolution canvas
 * via html2canvas, then either:
 *   • exports the canvas as a PNG, or
 *   • embeds it into a multi-page A4 PDF generated by jsPDF.
 *
 * No mock data — every label comes from the live PublicPassportBundle.
 */
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { getPublicPassportUrl } from '../utils/passportUrl';
import { isPassportExpired } from './passports';
import { logActivity } from './activity';
import type { PublicPassportBundle } from './publicPassport';

const TARGET_ID = 'skillproof-vip-passport-card';

const COLORS = {
  navy: '#0f172a',
  red: '#ED1C24',
  orange: '#F58220',
  gold: '#FFB000',
  amber: '#fbbf24',
  emerald: '#10b981',
  slate: '#475569',
  white: '#ffffff',
};

function ensureCard(bundle: PublicPassportBundle): HTMLDivElement {
  // Render the card off-screen into a hidden container so the export
  // doesn't depend on what the user happens to be looking at.
  const host = document.createElement('div');
  host.id = 'skillproof-export-host';
  host.style.position = 'fixed';
  host.style.left = '-99999px';
  host.style.top = '0';
  host.style.zIndex = '-1';
  host.style.pointerEvents = 'none';
  host.appendChild(buildCardNode(bundle));
  document.body.appendChild(host);
  return host;
}

function cleanup(host: HTMLElement | null) {
  if (host?.parentNode) host.parentNode.removeChild(host);
}

function fmtDate(d: string | null | undefined): string {
  if (!d) return '—';
  try { return new Date(d).toLocaleDateString(); } catch { return '—'; }
}

function initials(name: string): string {
  return name
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((s) => s[0]!.toUpperCase())
    .join('');
}

/**
 * Programmatically build the VIP passport DOM node so the on-screen
 * layout is faithfully reproduced for export. We can't reuse React here
 * without mounting it, so we hand-craft the same premium enterprise
 * layout the user sees.
 */
function buildCardNode(bundle: PublicPassportBundle): HTMLElement {
  const { passport, profile, levelHistory, latestAssessmentScore, latestAssessmentAt } = bundle;
  const root = document.createElement('div');
  root.id = TARGET_ID;
  root.style.width = '980px';
  root.style.fontFamily = 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif';
  root.style.background = 'linear-gradient(135deg, #0f172a 0%, #7f1d1d 50%, #9a3412 100%)';
  root.style.color = COLORS.white;
  root.style.borderRadius = '24px';
  root.style.overflow = 'hidden';
  root.style.padding = '32px';
  root.style.position = 'relative';

  const expired = isPassportExpired(passport);
  const isActive = passport.status === 'active' && !expired;
  const isPending = passport.status === 'pending_approval';
  const isRejected = passport.status === 'rejected';
  const publicUrl = getPublicPassportUrl(passport.passport_number);

  // === Header row ===
  const header = document.createElement('div');
  header.style.display = 'flex';
  header.style.justifyContent = 'space-between';
  header.style.alignItems = 'center';
  header.style.paddingBottom = '20px';
  header.style.borderBottom = '1px solid rgba(255,255,255,0.15)';

  const headerLeft = document.createElement('div');
  headerLeft.innerHTML = `
    <div style="display:flex;align-items:center;gap:10px;">
      <div style="width:36px;height:36px;border-radius:10px;background:linear-gradient(135deg,#ED1C24,#F58220,#FFB000);display:flex;align-items:center;justify-content:center;font-weight:900;color:#fff;font-size:18px;">S</div>
      <div>
        <div style="font-size:13px;font-weight:800;letter-spacing:0.25em;color:#FDE68A;">SKILLPROOF</div>
        <div style="font-size:10px;color:#FCD34D;">OFFICIAL PASSPORT</div>
      </div>
    </div>
  `;
  const headerRight = document.createElement('div');
  headerRight.innerHTML = `
    <div style="display:flex;align-items:center;gap:8px;">
      <span style="display:inline-flex;align-items:center;gap:6px;background:${
        isActive ? 'rgba(16,185,129,0.2)' : isPending ? 'rgba(251,191,36,0.2)' : isRejected ? 'rgba(244,63,94,0.25)' : 'rgba(244,63,94,0.2)'
      };padding:4px 10px;border-radius:999px;font-size:11px;font-weight:700;color:${
        isActive ? '#A7F3D0' : isPending ? '#FEF3C7' : isRejected ? '#FECDD3' : '#FECDD3'
      };">
        ${isActive ? '✓ VERIFIED' : isPending ? '⏱ PENDING' : isRejected ? '✕ REJECTED' : expired ? '⏱ EXPIRED' : passport.status.toUpperCase()}
      </span>
      <span style="display:inline-flex;align-items:center;gap:6px;background:rgba(255,255,255,0.1);padding:4px 12px;border-radius:999px;font-size:11px;font-weight:800;color:#fff;text-transform:uppercase;">
        ${levelIcon(passport.level)} ${passport.level}
      </span>
    </div>
  `;
  header.appendChild(headerLeft);
  header.appendChild(headerRight);
  root.appendChild(header);

  // === Body row: identity + QR + seal ===
  const body = document.createElement('div');
  body.style.display = 'grid';
  body.style.gridTemplateColumns = '1fr 220px';
  body.style.gap = '28px';
  body.style.marginTop = '24px';

  // LEFT column
  const left = document.createElement('div');

  const identity = document.createElement('div');
  identity.style.display = 'flex';
  identity.style.gap = '16px';
  identity.style.alignItems = 'flex-start';

  const avatar = document.createElement('div');
  avatar.style.width = '96px';
  avatar.style.height = '96px';
  avatar.style.borderRadius = '20px';
  avatar.style.flexShrink = '0';
  avatar.style.boxShadow = '0 4px 12px rgba(0,0,0,0.3)';
  if (profile.avatar_url) {
    avatar.style.backgroundImage = `url(${profile.avatar_url})`;
    avatar.style.backgroundSize = 'cover';
    avatar.style.backgroundPosition = 'center';
  } else {
    avatar.style.background = 'linear-gradient(135deg,#fbbf24,#dc2626)';
    avatar.style.display = 'flex';
    avatar.style.alignItems = 'center';
    avatar.style.justifyContent = 'center';
    avatar.style.fontSize = '36px';
    avatar.style.fontWeight = '900';
    avatar.style.color = '#fff8e1';
    avatar.textContent = initials(profile.full_name);
  }
  identity.appendChild(avatar);

  const nameBlock = document.createElement('div');
  nameBlock.style.flex = '1';
  nameBlock.innerHTML = `
    <div style="font-size:28px;font-weight:900;line-height:1.1;letter-spacing:-0.01em;">${escapeHtml(profile.full_name)}</div>
    ${profile.current_position ? `<div style="margin-top:6px;font-size:13px;color:#FCD34D;">${escapeHtml(profile.current_position)}</div>` : ''}
    <div style="margin-top:10px;display:flex;flex-wrap:wrap;gap:6px;">
      <span style="display:inline-flex;align-items:center;gap:5px;background:rgba(255,255,255,0.1);padding:3px 9px;border-radius:999px;font-family:monospace;font-size:11px;font-weight:700;color:#FDE68A;">
        #${escapeHtml(passport.passport_number)}
      </span>
      ${passport.main_category_name ? `<span style="display:inline-flex;align-items:center;gap:5px;background:rgba(251,191,36,0.2);padding:3px 9px;border-radius:999px;font-size:11px;font-weight:700;color:#FEF3C7;">${escapeHtml(passport.main_category_name)}</span>` : ''}
      ${profile.district ? `<span style="display:inline-flex;align-items:center;gap:5px;background:rgba(56,189,248,0.2);padding:3px 9px;border-radius:999px;font-size:11px;font-weight:700;color:#BAE6FD;">${escapeHtml(profile.district)}, ${escapeHtml(profile.country ?? 'Bangladesh')}</span>` : ''}
    </div>
  `;
  identity.appendChild(nameBlock);
  left.appendChild(identity);

  // Skill tags
  if (passport.skill_tags && passport.skill_tags.length > 0) {
    const tagsWrap = document.createElement('div');
    tagsWrap.style.marginTop = '18px';
    tagsWrap.innerHTML = `<div style="font-size:10px;font-weight:700;letter-spacing:0.2em;color:#FCD34D;text-transform:uppercase;margin-bottom:8px;">VERIFIED SKILL TAGS</div>`;
    const tagsRow = document.createElement('div');
    tagsRow.style.display = 'flex';
    tagsRow.style.flexWrap = 'wrap';
    tagsRow.style.gap = '6px';
    for (const tag of passport.skill_tags) {
      const t = document.createElement('span');
      t.style.background = 'rgba(255,255,255,0.1)';
      t.style.padding = '4px 10px';
      t.style.borderRadius = '999px';
      t.style.fontSize = '11px';
      t.style.color = '#FEF3C7';
      t.textContent = tag;
      tagsRow.appendChild(t);
    }
    tagsWrap.appendChild(tagsRow);
    left.appendChild(tagsWrap);
  }

  // Stats
  const stats = document.createElement('div');
  stats.style.marginTop = '18px';
  stats.style.display = 'grid';
  stats.style.gridTemplateColumns = 'repeat(4,1fr)';
  stats.style.gap = '10px';
  const statDefs = [
    { label: 'PASSED', value: String(passport.passed_count ?? 0) },
    { label: 'AVG / 10', value: Number(passport.average_marks ?? 0).toFixed(1) },
    { label: 'OVERALL / 100', value: passport.overall_score ? String(passport.overall_score) : '—' },
    { label: 'LATEST', value: latestAssessmentScore != null ? `${latestAssessmentScore.toFixed(1)}/10` : '—' },
  ];
  for (const s of statDefs) {
    const cell = document.createElement('div');
    cell.style.background = 'rgba(255,255,255,0.06)';
    cell.style.border = '1px solid rgba(255,255,255,0.12)';
    cell.style.padding = '10px';
    cell.style.borderRadius = '10px';
    cell.style.textAlign = 'center';
    cell.innerHTML = `
      <div style="font-size:9px;font-weight:700;letter-spacing:0.2em;color:#FCD34D;text-transform:uppercase;">${s.label}</div>
      <div style="font-size:18px;font-weight:900;color:#fff;margin-top:3px;">${s.value}</div>
    `;
    stats.appendChild(cell);
  }
  left.appendChild(stats);

  // Dates
  const dates = document.createElement('div');
  dates.style.marginTop = '18px';
  dates.style.display = 'grid';
  dates.style.gridTemplateColumns = 'repeat(3,1fr)';
  dates.style.gap = '10px';
  dates.style.background = 'rgba(255,255,255,0.05)';
  dates.style.border = '1px solid rgba(255,255,255,0.1)';
  dates.style.padding = '12px';
  dates.style.borderRadius = '14px';
  dates.innerHTML = `
    <div>
      <div style="font-size:10px;font-weight:700;letter-spacing:0.2em;color:#FCD34D;text-transform:uppercase;">ISSUED</div>
      <div style="font-size:14px;font-weight:700;margin-top:3px;">${fmtDate(passport.issue_date)}</div>
    </div>
    <div>
      <div style="font-size:10px;font-weight:700;letter-spacing:0.2em;color:#FCD34D;text-transform:uppercase;">APPROVED</div>
      <div style="font-size:14px;font-weight:700;margin-top:3px;">${fmtDate(passport.signed_at ?? passport.issue_date)}</div>
    </div>
    <div>
      <div style="font-size:10px;font-weight:700;letter-spacing:0.2em;color:${expired ? '#FDA4AF' : '#FCD34D'};text-transform:uppercase;">${expired ? 'EXPIRED' : 'EXPIRES'}</div>
      <div style="font-size:14px;font-weight:700;margin-top:3px;color:${expired ? '#FDA4AF' : '#fff'};">${fmtDate(passport.expiry_date)}</div>
    </div>
  `;
  left.appendChild(dates);

  // Digital signature
  if (passport.digital_signature) {
    const sig = document.createElement('div');
    sig.style.marginTop = '16px';
    sig.style.padding = '12px';
    sig.style.background = 'rgba(0,0,0,0.25)';
    sig.style.border = '1px solid rgba(255,255,255,0.1)';
    sig.style.borderRadius = '10px';
    sig.innerHTML = `
      <div style="font-size:10px;font-weight:700;letter-spacing:0.25em;color:#FCD34D;text-transform:uppercase;">DIGITAL SIGNATURE</div>
      <div style="font-family:monospace;font-size:10px;color:#FDE68A;margin-top:4px;word-break:break-all;">${escapeHtml(passport.digital_signature)}</div>
      ${passport.signed_at ? `<div style="font-size:9px;color:#FDE68A;margin-top:4px;">Signed ${new Date(passport.signed_at).toLocaleString()}</div>` : ''}
    `;
    left.appendChild(sig);
  }

  body.appendChild(left);

  // RIGHT column (QR + verification URL + seal)
  const right = document.createElement('div');
  right.style.display = 'flex';
  right.style.flexDirection = 'column';
  right.style.alignItems = 'center';
  right.style.gap = '14px';
  right.style.background = 'rgba(255,255,255,0.05)';
  right.style.padding = '20px';
  right.style.borderRadius = '16px';
  right.style.border = '1px solid rgba(255,255,255,0.1)';

  // Seal (SVG inline)
  right.innerHTML = `
    <svg viewBox="0 0 200 200" width="100" height="100" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <radialGradient id="sealbg" cx="50%" cy="40%" r="65%">
          <stop offset="0%" stop-color="#fbbf24"/>
          <stop offset="55%" stop-color="#dc2626"/>
          <stop offset="100%" stop-color="#7f1d1d"/>
        </radialGradient>
      </defs>
      <circle cx="100" cy="100" r="60" fill="url(#sealbg)" stroke="#fef3c7" stroke-width="3"/>
      <text x="100" y="105" text-anchor="middle" font-size="36" font-weight="800" fill="#fff8e1" font-family="Georgia,serif">SP</text>
      <text x="100" y="128" text-anchor="middle" font-size="9" font-weight="600" fill="#fef3c7" letter-spacing="2">SKILLPROOF</text>
    </svg>
  `;

  // QR placeholder — html2canvas will pick up the inline <svg> but QR
  // needs to be drawn separately as a canvas → image for crispness.
  const qrHolder = document.createElement('div');
  qrHolder.style.background = '#fff';
  qrHolder.style.padding = '10px';
  qrHolder.style.borderRadius = '12px';
  qrHolder.style.boxShadow = '0 4px 12px rgba(0,0,0,0.25)';
  const qrImg = document.createElement('img');
  qrImg.crossOrigin = 'anonymous';
  qrImg.src = qrUrl(publicUrl);
  qrImg.style.width = '160px';
  qrImg.style.height = '160px';
  qrImg.style.display = 'block';
  qrHolder.appendChild(qrImg);
  right.appendChild(qrHolder);

  const urlText = document.createElement('div');
  urlText.style.fontSize = '9px';
  urlText.style.fontFamily = 'monospace';
  urlText.style.color = '#FDE68A';
  urlText.style.textAlign = 'center';
  urlText.style.wordBreak = 'break-all';
  urlText.style.maxWidth = '180px';
  urlText.textContent = publicUrl;
  right.appendChild(urlText);

  body.appendChild(right);
  root.appendChild(body);

  // === Footer ===
  const footer = document.createElement('div');
  footer.style.marginTop = '24px';
  footer.style.paddingTop = '16px';
  footer.style.borderTop = '1px solid rgba(255,255,255,0.15)';
  footer.style.display = 'flex';
  footer.style.justifyContent = 'space-between';
  footer.style.alignItems = 'center';
  footer.style.fontSize = '10px';
  footer.style.color = '#FDE68A';
  footer.innerHTML = `
    <div>
      <div style="font-weight:800;letter-spacing:0.2em;">SKILLPROOF BANGLADESH</div>
      <div style="color:#FCD34D;margin-top:2px;">Official Verified Passport · ${passport.passport_number}</div>
    </div>
    <div style="text-align:right;">
      <div>Verified at ${escapeHtml(publicUrl)}</div>
      <div style="margin-top:2px;">Generated ${new Date().toLocaleString()}</div>
    </div>
  `;
  root.appendChild(footer);

  // Excluded audit hidden markers
  if (levelHistory.length > 0) {
    const auditWrap = document.createElement('div');
    auditWrap.style.marginTop = '14px';
    auditWrap.style.fontSize = '9px';
    auditWrap.style.color = '#FDE68A';
    auditWrap.style.opacity = '0.85';
    const last = levelHistory[0];
    auditWrap.textContent = `Level history: ${levelHistory.length} record(s) · Latest: ${last.old_level} → ${last.new_level} on ${new Date(last.changed_at).toLocaleDateString()}`;
    root.appendChild(auditWrap);
  }

  return root;
}

function qrUrl(data: string): string {
  // Use a public QR service for export (no client-side drawing of QR).
  // This avoids bundling another QR lib for export.
  const encoded = encodeURIComponent(data);
  return `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encoded}&color=0f172a&bgcolor=ffffff`;
}

function levelIcon(level: string): string {
  // Return SVG path snippet for the level icon.
  switch (level) {
    case 'Bronze': return '★';
    case 'Silver': return '★';
    case 'Gold': return '★';
    case 'Platinum': return '★';
    default: return '★';
  }
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Snapshot the VIP passport card to a high-resolution PNG. Triggers
 * a browser download.
 */
export async function downloadPassportPng(bundle: PublicPassportBundle): Promise<void> {
  const host = ensureCard(bundle);
  const node = host.firstElementChild as HTMLElement;
  try {
    const canvas = await html2canvas(node, {
      backgroundColor: '#0f172a',
      scale: 2,
      useCORS: true,
      logging: false,
      allowTaint: true,
    });
    const link = document.createElement('a');
    link.download = `SkillProof-Passport-${bundle.passport.passport_number}.png`;
    link.href = canvas.toDataURL('image/png');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    void logActivity('passport.downloaded', `Downloaded passport ${bundle.passport.passport_number} (PNG)`, {
      entityType: 'skill_passport',
      entityId: bundle.passport.id,
      metadata: { format: 'png', passport_number: bundle.passport.passport_number },
    });
  } finally {
    cleanup(host);
  }
}

/**
 * Snapshot the VIP passport card and embed it into a multi-page A4 PDF
 * (the card on page 1, a "verification" page with timeline on page 2).
 */
export async function downloadPassportPdf(bundle: PublicPassportBundle): Promise<void> {
  const host = ensureCard(bundle);
  const node = host.firstElementChild as HTMLElement;
  try {
    const canvas = await html2canvas(node, {
      backgroundColor: '#0f172a',
      scale: 2,
      useCORS: true,
      logging: false,
      allowTaint: true,
    });
    const imgData = canvas.toDataURL('image/png');

    const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
    const pageW = pdf.internal.pageSize.getWidth();
    const pageH = pdf.internal.pageSize.getHeight();

    // Fit image to page with margins.
    const margin = 8;
    const ratio = canvas.width / canvas.height;
    let imgW = pageW - margin * 2;
    let imgH = imgW / ratio;
    if (imgH > pageH - margin * 2) {
      imgH = pageH - margin * 2;
      imgW = imgH * ratio;
    }
    const imgX = (pageW - imgW) / 2;
    const imgY = (pageH - imgH) / 2;
    pdf.addImage(imgData, 'PNG', imgX, imgY, imgW, imgH);

    // === Page 2: Verification summary ===
    pdf.addPage();
    const { passport, profile, levelHistory, renewalHistory, latestAssessmentScore, latestAssessmentAt } = bundle;
    const publicUrl = getPublicPassportUrl(passport.passport_number);

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(20);
    pdf.setTextColor(15, 23, 42);
    pdf.text('SkillProof Passport Verification Record', margin, 18);

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(10);
    pdf.setTextColor(71, 85, 105);
    pdf.text(`Passport ID: ${passport.passport_number}`, margin, 28);
    pdf.text(`Holder: ${profile.full_name}`, margin, 34);
    pdf.text(`Main Category: ${passport.main_category_name ?? '—'}`, margin, 40);
    pdf.text(`Level: ${passport.level}`, margin, 46);
    pdf.text(`Status: ${passport.status}`, margin, 52);
    pdf.text(`Issue Date: ${fmtDate(passport.issue_date)}`, margin, 58);
    pdf.text(`Expiry Date: ${fmtDate(passport.expiry_date)}`, margin, 64);
    pdf.text(`Passed Assessments: ${passport.passed_count}`, margin, 70);
    pdf.text(`Average Marks: ${Number(passport.average_marks ?? 0).toFixed(1)} / 10`, margin, 76);
    pdf.text(`Overall Score: ${passport.overall_score ?? '—'} / 100`, margin, 82);
    if (latestAssessmentScore != null) {
      pdf.text(`Latest Score: ${latestAssessmentScore.toFixed(1)} / 10 (${latestAssessmentAt ? fmtDate(latestAssessmentAt) : '—'})`, margin, 88);
    }

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.setTextColor(237, 28, 36);
    pdf.text('Verification URL', margin, 102);
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9);
    pdf.setTextColor(15, 23, 42);
    pdf.text(publicUrl, margin, 108, { maxWidth: pageW - margin * 2 });

    if (passport.digital_signature) {
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(12);
      pdf.setTextColor(237, 28, 36);
      pdf.text('Digital Signature', margin, 120);
      pdf.setFont('courier', 'normal');
      pdf.setFontSize(8);
      pdf.setTextColor(71, 85, 105);
      pdf.text(passport.digital_signature, margin, 126, { maxWidth: pageW - margin * 2 });
    }

    if (levelHistory.length > 0) {
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(12);
      pdf.setTextColor(237, 28, 36);
      pdf.text('Level History', margin, 140);
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      pdf.setTextColor(15, 23, 42);
      let y = 146;
      for (const l of levelHistory.slice(0, 8)) {
        pdf.text(`${new Date(l.changed_at).toLocaleDateString()} · ${l.old_level} → ${l.new_level}${l.reason ? ' — ' + l.reason : ''}`, margin, y, { maxWidth: pageW - margin * 2 });
        y += 6;
        if (y > pageH - 20) break;
      }
    }

    if (renewalHistory.length > 0) {
      const yStart = 180;
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(12);
      pdf.setTextColor(237, 28, 36);
      pdf.text('Renewal History', margin, yStart);
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      pdf.setTextColor(15, 23, 42);
      let y = yStart + 6;
      for (const r of renewalHistory.slice(0, 6)) {
        const decision = r.decision ?? 'pending';
        pdf.text(`${new Date(r.requested_at).toLocaleDateString()} · ${decision}${r.decided_at ? ' (' + new Date(r.decided_at).toLocaleDateString() + ')' : ''}`, margin, y, { maxWidth: pageW - margin * 2 });
        y += 6;
        if (y > pageH - 10) break;
      }
    }

    pdf.save(`SkillProof-Passport-${passport.passport_number}.pdf`);
    void logActivity('passport.downloaded', `Downloaded passport ${passport.passport_number} (PDF)`, {
      entityType: 'skill_passport',
      entityId: passport.id,
      metadata: { format: 'pdf', passport_number: passport.passport_number },
    });
  } finally {
    cleanup(host);
  }
}