/* eslint-disable react/no-unescaped-entities */

/**
 * CareerSummarySection
 * --------------------
 * "Professional Summary" block. Renders whichever existing AI / profile
 * summary the candidate has on file. Honours the privacy gates — if
 * the candidate has hidden the AI career profile section we suppress
 * the AI summary too.
 *
 * Source fields (in priority order):
 *   1. ai_career_profile.career_summary
 *   2. career_information.experience_summary
 *   3. candidate.experience_summary
 *   4. career_information.bio
 *   5. candidate.bio
 *
 * Hidden entirely when no summary exists.
 */

import React from 'react';
import { FileText, Sparkles } from 'lucide-react';
import { Section, safeStr } from './profileHelpers';

interface Props {
  payload: any;
}

export function CareerSummarySection({ payload }: Props) {
  const hideAi = Boolean(
    payload?.hide_ai_on_verified_profile ?? payload?.candidate?.hide_ai_on_verified_profile ?? false,
  );

  const aiSummary = !hideAi ? safeStr(payload?.ai_career_profile?.career_summary ?? null) : null;
  const career = payload?.career_information ?? null;
  const candidate = payload?.candidate ?? null;

  const summary =
    aiSummary ??
    safeStr(career?.experience_summary ?? null) ??
    safeStr(candidate?.experience_summary ?? null) ??
    safeStr(career?.bio ?? null) ??
    safeStr(candidate?.bio ?? null);

  if (!summary) return null;

  // Split into paragraphs for readability when the summary is long.
  const paragraphs = summary
    .split(/\n\s*\n/)
    .map((p) => p.trim())
    .filter(Boolean);

  return (
    <Section
      id="career-summary"
      eyebrow="Professional Summary"
      title={aiSummary ? 'AI Career Summary' : 'Career Summary'}
      icon={<FileText className="h-4 w-4" />}
      helper={
        aiSummary
          ? 'Generated from the candidate\u2019s verified SkillProof profile.'
          : 'From the candidate\u2019s SkillProof profile.'
      }
      badge={aiSummary ? 'SkillProof AI' : undefined}
    >
      <div className="space-y-3">
        {paragraphs.length === 1 ? (
          <p className="text-sm leading-relaxed text-slate-800 break-words">{paragraphs[0]}</p>
        ) : (
          paragraphs.map((para, idx) => (
            <p
              key={idx}
              className="text-sm leading-relaxed text-slate-800 break-words"
            >
              {para}
            </p>
          ))
        )}
        {aiSummary ? (
          <p className="mt-2 inline-flex items-center gap-1 rounded-full bg-amber-50 px-2 py-0.5 text-[10px] font-semibold text-amber-700">
            <Sparkles className="h-3 w-3" /> Generated by SkillProof AI
          </p>
        ) : null}
      </div>
    </Section>
  );
}
